// ============================================
// AUTHENTICATION API
// ============================================
// All authentication-related Supabase operations
// Ready for production - just needs real Supabase connection

import { supabase } from '../lib/supabase';
import { isBackendDomainRejection, UNTRUSTED_DOMAIN_MESSAGE } from '../lib/emailValidator';
import type { ApiResponse, User, Profile, AuthSession } from '../types';

// ============================================
// SIGN UP
// ============================================

export async function signUp(email: string, password: string): Promise<ApiResponse<AuthSession>> {
  try {
    const { data, error } = await supabase.auth.signUp({
      email,
      password,
      options: {
        emailRedirectTo: `${window.location.origin}/onboarding`,
      },
    });

    if (error) {
      // Security fallback: map backend trigger rejection to clean user-facing message
      if (isBackendDomainRejection(error.message)) {
        return { data: null, error: { message: UNTRUSTED_DOMAIN_MESSAGE } };
      }
      return { data: null, error: { message: error.message } };
    }

    if (!data.user) {
      return { data: null, error: { message: 'Sign up failed' } };
    }



    // Create mock Profile with defunct fields to keep frontend compile-safe and fully backward-compatible
    const newProfile: Profile = {
      id: '', // Will be generated by Supabase
      user_id: data.user.id,
      role: undefined,
      business_stage: undefined,
      blocker: undefined,
      avg_project_value: undefined,
      onboarding_complete: false,
      follow_up_interval: 3,
      risk_threshold: 5,
      notifications_follow_up: true,
      notifications_proposal: true,
      notifications_lead: true,
      notifications_weekly: false,
      full_name: '',
      notify_followup_reminders: true,
      notify_proposal_updates: true,
      notify_lead_activity: true,
      notify_weekly_digest: false,
      default_followup_interval_days: 3,
      risk_alert_threshold_days: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    // Database-compatible profile structure (only contains valid schema columns)
    const dbProfile = {
      user_id: data.user.id,
      onboarding_complete: false,
      full_name: '',
      notify_followup_reminders: true,
      notify_proposal_updates: true,
      notify_lead_activity: true,
      notify_weekly_digest: false,
      default_followup_interval_days: 3,
      risk_alert_threshold_days: 5,
      created_at: newProfile.created_at,
      updated_at: newProfile.updated_at,
    };

    // Don't use .select() after INSERT to avoid RLS re-evaluation issues
    // Do NOT fail signup if profile creation fails, since auth account is successfully created and email dispatched.
    const { error: profileError } = await supabase
      .from('profiles')
      .upsert(dbProfile, { onConflict: 'user_id' });

    if (profileError) {
      console.warn('[AUTH] Profile insertion skipped or failed during signUp (handled gracefully):', profileError);
    }

    // Seed default message templates
    try {
      await seedTemplates(data.user.id);
    } catch (templateError) {
      console.warn('[AUTH] Template seeding failed during signUp (handled gracefully):', templateError);
    }

    return {
      data: {
        user: data.user as User,
        profile: newProfile as Profile,
        access_token: data.session?.access_token,
        refresh_token: data.session?.refresh_token,
      },
      error: null,
    };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

// ============================================
// SIGN IN
// ============================================

export async function signIn(email: string, password: string): Promise<ApiResponse<AuthSession>> {
  try {
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    if (error) {
      return { data: null, error: { message: error.message } };
    }

    if (!data.user) {
      return { data: null, error: { message: 'Sign in failed' } };
    }



    // Get user profile
    const profileResult = await getProfile(data.user.id);

    if (profileResult.error) {
      return { data: null, error: profileResult.error };
    }

    return {
      data: {
        user: data.user as User,
        profile: profileResult.data!,
        access_token: data.session?.access_token,
        refresh_token: data.session?.refresh_token,
      },
      error: null,
    };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

// ============================================
// SIGN OUT
// ============================================

export async function signOut(): Promise<ApiResponse<void>> {
  try {
    const { error } = await supabase.auth.signOut();

    if (error) {
      return { data: null, error: { message: error.message } };
    }

    return { data: null, error: null };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

// ============================================
// GET CURRENT SESSION
// ============================================

export async function getCurrentSession(): Promise<ApiResponse<AuthSession>> {
  try {
    const { data, error } = await supabase.auth.getSession();

    if (error || !data.session) {
      return { data: null, error: { message: 'No active session' } };
    }



    const profileResult = await getProfile(data.session.user.id);

    if (profileResult.error) {
      // If profile fetch fails (e.g., 406), return without profile
      console.warn('Profile fetch failed:', profileResult.error);
      return {
        data: {
          user: data.session.user as User,
          profile: null as any,
          access_token: data.session.access_token,
          refresh_token: data.session.refresh_token,
        },
        error: null,
      };
    }

    return {
      data: {
        user: data.session.user as User,
        profile: profileResult.data!,
        access_token: data.session.access_token,
        refresh_token: data.session.refresh_token,
      },
      error: null,
    };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

// ============================================
// PROFILE OPERATIONS
// ============================================

export async function createProfile(userId: string): Promise<ApiResponse<Profile>> {
  try {
    const dbProfile = {
      user_id: userId,
      onboarding_complete: false,
      full_name: '',
      notify_followup_reminders: true,
      notify_proposal_updates: true,
      notify_lead_activity: true,
      notify_weekly_digest: false,
      default_followup_interval_days: 3,
      risk_alert_threshold_days: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    // Don't use .select() after INSERT to avoid RLS re-evaluation issues
    const { error } = await supabase
      .from('profiles')
      .insert(dbProfile);

    if (error) {
      return { data: null, error: { message: error.message } };
    }

    const fallbackProfile: Profile = {
      id: '',
      user_id: userId,
      onboarding_complete: false,
      follow_up_interval: 3,
      risk_threshold: 5,
      notifications_follow_up: true,
      notifications_proposal: true,
      notifications_lead: true,
      notifications_weekly: false,
      full_name: '',
      notify_followup_reminders: true,
      notify_proposal_updates: true,
      notify_lead_activity: true,
      notify_weekly_digest: false,
      default_followup_interval_days: 3,
      risk_alert_threshold_days: 5,
      created_at: dbProfile.created_at,
      updated_at: dbProfile.updated_at,
    };

    return { data: fallbackProfile, error: null };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

export async function getProfile(userId: string): Promise<ApiResponse<Profile>> {
  try {
    // Query without .select() first to avoid RLS issues
    const { data, error } = await supabase
      .from('profiles')
      .select('*')
      .eq('user_id', userId)
      .maybeSingle();

    if (error) {
      console.warn('Profile fetch error:', error);
      // Return a default profile instead of erroring out
      return {
        data: {
          id: '',
          user_id: userId,
          role: null,
          business_stage: null,
          blocker: null,
          avg_project_value: null,
          onboarding_complete: false,
          follow_up_interval: 3,
          risk_threshold: 5,
          notifications_follow_up: true,
          notifications_proposal: true,
          notifications_lead: true,
          notifications_weekly: false,
          full_name: '',
          notify_followup_reminders: true,
          notify_proposal_updates: true,
          notify_lead_activity: true,
          notify_weekly_digest: false,
          default_followup_interval_days: 3,
          risk_alert_threshold_days: 5,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        error: null,
      };
    }

    // If profile doesn't exist, auto-create it
    if (!data) {
      const newProfile: Profile = {
        id: '',
        user_id: userId,
        role: undefined,
        business_stage: undefined,
        blocker: undefined,
        avg_project_value: undefined,
        onboarding_complete: false,
        follow_up_interval: 3,
        risk_threshold: 5,
        notifications_follow_up: true,
        notifications_proposal: true,
        notifications_lead: true,
        notifications_weekly: false,
        full_name: '',
        notify_followup_reminders: true,
        notify_proposal_updates: true,
        notify_lead_activity: true,
        notify_weekly_digest: false,
        default_followup_interval_days: 3,
        risk_alert_threshold_days: 5,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };

      const dbProfile = {
        user_id: userId,
        onboarding_complete: false,
        full_name: '',
        notify_followup_reminders: true,
        notify_proposal_updates: true,
        notify_lead_activity: true,
        notify_weekly_digest: false,
        default_followup_interval_days: 3,
        risk_alert_threshold_days: 5,
        created_at: newProfile.created_at,
        updated_at: newProfile.updated_at,
      };

      const { data: createdProfile, error: createError } = await supabase
        .from('profiles')
        .upsert(dbProfile, { onConflict: 'user_id' })
        .select()
        .maybeSingle();

      if (createError) {
        console.warn('Failed to auto-create profile:', createError);
        // Return the default profile object even if insert fails
        return { data: newProfile as Profile, error: null };
      }

      // Seed templates if we just auto-created the profile
      try {
        await seedTemplates(userId);
      } catch (templateError) {
        console.warn('Template seeding failed in getProfile (handled gracefully):', templateError);
      }

      return {
        data: {
          ...newProfile,
          ...(createdProfile || {}),
        } as Profile,
        error: null,
      };
    }

    return { data: data as Profile, error: null };
  } catch (error: any) {
    console.warn('Profile fetch exception:', error);
    // Return default profile instead of failing
    return {
      data: {
        id: '',
        user_id: userId,
        role: null,
        business_stage: null,
        blocker: null,
        avg_project_value: null,
        onboarding_complete: false,
        follow_up_interval: 3,
        risk_threshold: 5,
        notifications_follow_up: true,
        notifications_proposal: true,
        notifications_lead: true,
        notifications_weekly: false,
        full_name: '',
        notify_followup_reminders: true,
        notify_proposal_updates: true,
        notify_lead_activity: true,
        notify_weekly_digest: false,
        default_followup_interval_days: 3,
        risk_alert_threshold_days: 5,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      error: null,
    };
  }
}

export async function updateProfile(userId: string, updates: Partial<Profile>): Promise<ApiResponse<Profile>> {
  try {
    const validDbKeys = [
      'role',
      'business_stage',
      'blocker',
      'avg_project_value',
      'onboarding_complete',
      'full_name',
      'notify_followup_reminders',
      'notify_proposal_updates',
      'notify_lead_activity',
      'notify_weekly_digest',
      'default_followup_interval_days',
      'risk_alert_threshold_days'
    ];

    const cleanUpdates: any = {};
    for (const key of Object.keys(updates)) {
      if (validDbKeys.includes(key)) {
        cleanUpdates[key] = (updates as any)[key];
      }
    }

    const updatesWithTimestamp = {
      ...cleanUpdates,
      updated_at: new Date().toISOString(),
    };

    // Don't use .select() after UPDATE due to RLS re-evaluation issues
    // Just perform the update and return the constructed profile
    const { error } = await supabase
      .from('profiles')
      .update(updatesWithTimestamp)
      .eq('user_id', userId);

    if (error) {
      return { data: null, error: { message: error.message } };
    }

    // First, try to get the full profile to ensure all fields are present
    const { data: fullProfile, error: fetchError } = await supabase
      .from('profiles')
      .select('*')
      .eq('user_id', userId)
      .maybeSingle();

    if (!fetchError && fullProfile) {
      return { data: fullProfile as Profile, error: null };
    }

    // If fetch fails due to RLS timing, construct profile from updates
    // This happens because RLS re-evaluates on SELECT after UPDATE
    // We trust the UPDATE succeeded if no error was returned
    console.warn('Profile fetch after update returned empty due to RLS timing, using partial profile');
    
    return {
      data: {
        id: '',
        user_id: userId,
        ...updatesWithTimestamp,
      } as Profile,
      error: null,
    };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

export async function completeOnboarding(
  userId: string,
  onboardingData: {
    full_name?: string;
    role?: string;
    business_stage?: string;
    blocker?: string;
    avg_project_value?: number;
  }
): Promise<ApiResponse<Profile>> {
  return updateProfile(userId, {
    ...onboardingData,
    onboarding_complete: true,
  });
}

// ============================================
// TEMPLATE SEEDING
// ============================================

async function seedTemplates(userId: string) {
  const defaultTemplates = [
    {
      user_id: userId,
      template_type: 'first_outreach',
      title: 'First Outreach',
      content: 'Hi {{name}},\n\nI noticed {{company}} is doing some great work. I help companies like yours scale with better systems.\n\nAre you open to a quick chat next week to see if there is a fit?\n\nBest,\n[Your Name]',
    },
    {
      user_id: userId,
      template_type: 'warm_recovery',
      title: 'Warm Recovery',
      content: 'Hey {{name}},\n\nJust floating this to the top of your inbox. Let me know if you still want to move forward, or if priorities have shifted.\n\nThanks!',
    },
    {
      user_id: userId,
      template_type: 'proposal_reminder',
      title: 'Proposal Reminder',
      content: 'Hi {{name}},\n\nHope you had a chance to review the proposal I sent over. I have some availability opening up next month and wanted to check if we should lock in your spot.\n\nLet me know if you have any questions on the pricing or timeline.',
    },
    {
      user_id: userId,
      template_type: 'pricing_followup',
      title: 'Pricing Follow-Up',
      content: 'Hey {{name}},\n\nFollowing up on our pricing discussion. I understand this is a significant investment. Should we jump on a 5-min call to adjust the scope to better fit your budget?\n\nLet me know what works.',
    }
  ];

  try {
    await supabase.from('message_templates').insert(defaultTemplates);
  } catch (error) {
    console.warn('Failed to seed templates:', error);
  }
}

// ============================================
// SIGN IN WITH GOOGLE (OAUTH)
// ============================================

export async function signInWithGoogle(): Promise<ApiResponse<void>> {
  try {
    const { error } = await supabase.auth.signInWithOAuth({
      provider: 'google',
      options: {
        redirectTo: `${window.location.origin}/onboarding`,
      },
    });
    if (error) {
      return { data: null, error: { message: error.message } };
    }
    return { data: null, error: null };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

// ============================================
// RESEND VERIFICATION EMAIL
// ============================================

export async function resendVerificationEmail(email: string): Promise<ApiResponse<void>> {
  try {
    const { error } = await supabase.auth.resend({
      type: 'signup',
      email,
      options: {
        emailRedirectTo: `${window.location.origin}/onboarding`,
      },
    });
    if (error) {
      return { data: null, error: { message: error.message } };
    }
    return { data: null, error: null };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

// ============================================
// CHANGE PASSWORD
// ============================================

export async function changePassword(newPassword: string): Promise<ApiResponse<void>> {
  try {
    const { error } = await supabase.auth.updateUser({ password: newPassword });
    if (error) {
      return { data: null, error: { message: error.message } };
    }
    return { data: null, error: null };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

// ============================================
// VERIFY CURRENT PASSWORD
// ============================================

export async function verifyCurrentPassword(email: string, currentPassword: string): Promise<ApiResponse<boolean>> {
  try {
    const { error } = await supabase.auth.signInWithPassword({
      email,
      password: currentPassword,
    });
    if (error) {
      return { data: false, error: { message: 'Incorrect current password. Please try again.' } };
    }
    return { data: true, error: null };
  } catch (error: any) {
    return { data: false, error: { message: error.message || 'Verification failed.' } };
  }
}

// ============================================
// SEND PASSWORD RESET EMAIL
// ============================================

export async function sendPasswordResetEmail(email: string): Promise<ApiResponse<void>> {
  try {
    const { error } = await supabase.auth.resetPasswordForEmail(email, {
      redirectTo: `${window.location.origin}/app/settings/security`,
    });
    if (error) {
      return { data: null, error: { message: error.message } };
    }
    return { data: null, error: null };
  } catch (error: any) {
    return { data: null, error: { message: error.message } };
  }
}

